### PR TITLE
Docstring for feedback components.

### PR DESCRIPTION
**Pull request by rishabsinghh**
Feature: Adding Docstrings to Feedback Components.

### CODE REVIEW

**Comment by jeffkayne** [comment]
Hello @rishabsinghh.

Thanks for your PR. A Couple of things:

- [ ] Could you fix the linting issues? You can consult the [CONTRIBUTING.md](https://github.com/trubrics/trubrics-sdk/blob/main/CONTRIBUTING.md) for info on how to run the linter locally
- [ ] There is no default specified for the "path" argument in all three functions. Could you remove references to this "defaults to current working directory" in all docstrings and parameter descriptions?
- [ ] file_name defaults to "feedback.json", not "Feedback.json"

**Comment by jeffkayne** [comment]
Hello @rishabsinghh 

Any updates on this?

Many thanks !

**Comment by rishabsinghh** [comment]
Hey Jeff, would finish this up this weekend. Sorry, have been stacked with work lately. I had a query though, i didn't get the linting issues part. Could you tell me a bit more about that?

**Comment by jeffkayne** [comment]
Hey @rishabsinghh 

No worries at all ! Yes so we use [black](https://github.com/psf/black) to auto format our code and make sure that it is homogeneous between developers. We also have another couple of formatting tools. 

To run this formatter, you can follow the steps [here](https://github.com/trubrics/trubrics-sdk/blob/main/CONTRIBUTING.md#your-first-contribution). Specifically, after installation of relevant packages with `make install-dev`, you can run `make lint` to auto format your code.

Let me know if you need any more help.

**Comment by rishabsinghh** [comment]
Hey Jeff, I am so sorry for delaying this. Was cramped with work, let me know your reviews.

**Comment by jeffkayne** [comment]
Hello @rishabsinghh 

No worries at all !
I have just fixed some last errors where some lines in the docstrings were too long (>120 chars) and that were being flagged by our CI.

Many thanks for the PR, I'm merging :)

**Comment by rishabsinghh** [comment]
Thank you Jeff. Would love to contribute on more issues and build together! Again, so sorry for the delay!

**Pull request merged**
